config/routes.rb
Rails.application.routes.draw do

  resources :articles
  get 'landing/index'
  root 'landing#index'

  get 'carousel/index'

  devise_for :users
  get 'persons/profile'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :header, presence: true,
            length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :timeoutable, :timeout_in => 10.minutes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]

  def new
    @article = Article.new
  end

  def index
    @articles = Article.all
  end

  def create
    @article =  Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:header, :article_body)
  end

end

app/controllers/carousel_controller.rb
class CarouselController < ApplicationController

  def index

  end

  def new

  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index

  end

  def new
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carousel_helper.rb
module CarouselHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/index.html.haml
-content_for :page_title do
  -t('title-articles')
%table{:class => 'border'}
  %tr
    %td
      HEADER
    %td
      CONTENT
  - @articles.each do |a|
    %tr
      %td
        =link_to a.header, article_path(:id => a.id)
      %td
        = a.article_body

app/views/articles/new.html.haml
-content_for :page_title do
  =t('title-new-article')
  %h1 Add article

%div{:class => 'Create', :id => 'create_article'}
=form_for :article, url: articles_path do |f|
  =if @article.errors.any?
    %div
      =pluralize(@article.errors.count, 'error')
    %ul
      =@article.errors.full_messages.each do |msg|
        %li
          =msg.to_s
  %div{:id => 'labels'}
    =f.label :article_header_label, 'Article name', :class => 'header_label'
    %br
    =f.label :article_body_label, 'Article body', :class => 'article_area'
  %div{:id => 'inputs'}
    =f.text_field :header
    %br
    =f.text_area :article_body
    %br
    =f.submit :class => 'button'

app/views/articles/show.html.haml
-content_for :page_title do
  =t('title-single-article')
  =@article.id
%h1
  Id is
  =@article.id
%div
  %table{:class => 'border'}
    %tr
      %td Title:
      %td
        =@article.header
    %tr
      %td Body:
      %td
        =@article.article_body

app/views/carousel/index.html.haml
%div{:id =>'carousel-example-generic', :class=>'carousel slide', 'data-ride' => 'carousel'}
  <!-- Indicators -->
  %ol.carousel-indicators
    %li{'data-target' => '#carousel-example-generic', 'data-slide-to' => '0', :class => 'active'}
    %li{'data-target' => '#carousel-example-generic', 'data-slide-to' => '1'}
    -#%li{'data-target' => '#carousel-example-generic', 'data-slide-to' => '2'}

  <!-- Wrapper for slides -->
  %div{:class => 'carousel-inner', :role => 'listbox'}
    %div.item
      =image_tag 'clouds.png'
      -#%img{:src => = stylesheet_path, :alt => '...'}
      %div.carousel-caption
    %div.item.active
      =image_tag 'road.jpg'
      -#%img{:src => '...', :alt => '...'}
      %div.carousel-caption

  <!-- Controls -->
  %a{:class => 'left carousel-control', :href => '#carousel-example-generic', :role => 'button', 'data-slide' => 'prev'}
    %span{:class => 'glyphicon glyphicon-chevron-left', 'aria-hidden' => 'true'}
    %span.sr-only Previous
  %a{:class => 'right carousel-control', :href => '#carousel-example-generic', :role => 'button', 'data-slide' => 'next'}
    %span{:class => 'glyphicon glyphicon-chevron-right', 'aria-hidden' => 'true'}
    %span.sr-only Next

app/views/landing/index.html.haml
-content_for :page_title do
  =t('title-index')
%h1 Welcome to sabaleuski.com
%div{:class => 'content'}
  -#=video_tag('GOPR0064.MP4', :width => 320, :height => 240, :controls => 'controls', :autoplay=> 'autoplay')

app/views/layouts/_footer.html.haml
%div.modal-footer
  %span Copyright: Ivan Sabaleuski 2016

app/views/layouts/_header.html.haml
%div.header
  -#%div{:class => 'login'}
  -# Device view moved to header menu
    -#= image_tag('GOPR0016.JPG')
    -#- unless user_signed_in?
    -#  =link_to 'Login', new_user_session_path, :class => 'button'
    -#  =link_to 'Sing up', new_user_registration_path, :class => 'button'
    -#- if user_signed_in?
    -#  =link_to 'Sign out', destroy_user_session_path, :class => 'button',  :method => :delete
    -#=yield :login
    -#%p{:class => 'notice'}
    -#=notice
    -#%p{:class => 'alert'}
    -#=alert

app/views/layouts/_menu.html.haml
%div{:class => 'left_menu'}
  =link_to 'Main page', landing_index_path, :class => 'menu_item'
  %br
  =link_to 'Articles', articles_path, :class => 'menu_item'
  %br
  =link_to 'New article', new_article_path, :class => 'menu_item' if user_signed_in?
  %br
  =link_to 'Carousel', carousel_index_path, :class => 'menu_item'

app/views/layouts/_top_menu.html.haml
%nav{:class => 'navbar navbar-inverse'}
  %div{:class => 'container-fluid'}
    -#<!-- Brand and toggle get grouped for better mobile display -->
    %div{:class => 'navbar-header'}
      -#%button{:type => 'button', :class => 'navbar-toggle collapsed',
      -#'data-toggle' =>'collapse',
      -#'data-target' => '#bs-example-navbar-collapse-1',
      -#'aria-expanded' => 'false'}
      -#  %span{:class => 'sr-only'} Toggle navigation
      -#  %span{:class => 'icon-bar'}
      -#  %span{:class => 'icon-bar'}
      =link_to landing_index_path, {class: 'navbar-brand'} do
        sabaleuski.com

    %div{class: 'collapse navbar-collapse', :id => 'bs-example-navbar-collapse-1'}
      %ul{:class =>"nav navbar-nav"}
        %li{class: 'active'}
          =link_to landing_index_path do
            Home
            %span{:class => "sr-only"}
        %li{class: 'dropdown'}
          =link_to articles_path, {class: 'dropdown-toggle',
              'data-toggle' => 'dropdown', role: 'button',
              'aria-haspopup' => 'true', 'aria-expanded' => 'false'} do
            Articles
            %span{class: 'caret'}
          %ul{class: 'dropdown-menu'}
            %li
              =link_to  'All articles', articles_path
            %li
              %a{href: '#'} Another action
            %li
              %a{href: '#'} Something else here
            %li{role: 'separator', class: 'divider'}
            %li
              %a{href:'#'} Separated link
        %li{:class => 'dropdown'}
          =link_to '#', {class: 'dropdown-toggle',
              'data-toggle' => 'dropdown', role: 'button',
              'aria-haspopup' => 'true', 'aria-expanded' => 'false'} do
            Galleries
            %span{class: 'caret'}
          %ul{class: 'dropdown-menu'}
            %li
              %a{href: '#'} Action
            %li
              %a{href: '#'} Another action
            %li
              %a{href: '#'} Something else here
            %li{role: 'separator', class: 'divider'}
            %li
              %a{href:'#'} Separated link
            %li{role: 'separator', class: 'divider'}
            %li
              %a{href: '#'} One more separated link
        %li{:class => 'dropdown'}
          =link_to '#', {class: 'dropdown-toggle',
            'data-toggle' => 'dropdown', role: 'button',
            'aria-haspopup' => 'true', 'aria-expanded' => 'false'} do
            Videos
            %span{class: 'caret'}
          %ul{class: 'dropdown-menu'}
            %li
              %a{href: '#'} Action
            %li
              %a{href: '#'} Another action
            %li
              %a{href: '#'} Something else here
            %li{role: 'separator', class: 'divider'}
            %li
              %a{href:'#'} Separated link
            %li{role: 'separator', class: 'divider'}
            %li
              %a{href: '#'} One more separated link
      %ul{class: 'nav navbar-nav navbar-right'}
        - unless user_signed_in?
          %li
            =link_to '#collapse1', {'data-toggle' => 'collapse'} do
              %span{class: 'glyphicon glyphicon-log-in'}
              New login
            %div{id: 'collapse1', class: 'panel-collapse collapse'}
              %ul{class: 'list-group'}
                %li{class: 'list-group-item'} lal
                %li{class: 'list-group-item'} lalalal
                %li{class: 'list-group-item'} blalba
          %li
            =link_to new_user_session_path do
              %span{class: 'glyphicon glyphicon-log-in'}
              Login

            -#=form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
            -#  %div{:class => 'field'}
            -#    = f.email_field :email, autofocus: true, :placeholder => 'email'
              %li
                lala
              %li
                blabla
          %li
            =link_to new_user_registration_path do
              %span{class: 'glyphicon glyphicon-user'}
              Sign up
        - if user_signed_in?
          %li
            =link_to destroy_user_session_path, method: :delete do
              %span{class: 'glyphicon glyphicon-log-out'}
              Log out
        =yield :login
        -#%p{:class => 'notice'}
        -#=notice
        %p{:class => 'alert'}
        =alert

app/views/layouts/application.html.haml
!!!
%html{:lang =>'en'}
  %head
    %title
      =yield :page_title if content_for :page_title
      =t('title-default') unless content_for :page_title
    =csrf_meta_tags
    =stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    =javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %div{class: 'container'}
      = render 'layouts/top_menu'
      = render 'layouts/header'
      = render 'layouts/menu'
      %div{:class => 'main_content'}
        =yield
      = render 'layouts/footer'

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>